### ISSUE TITLE
Multiple role for user 

### ISSUE THREAD

**Issue by vtrkanna** [TheRole/the_role_api#11]
Hi

t.integer  "role_id

we tried with single role user its working  fine

How to maintain multiple role for user.

**Comment by the-teacher** [comment]
https://github.com/TheRole/docs/blob/master/Limitations.md#user-has-only-one-role

**Comment by vtrkanna** [comment]
Is it possible overwrite  has-only-one-role to has-many

**Comment by the-teacher** [comment]
@vtrkanna

hello! of course you can do everything with code. You can use the_role way to store access rules into database. But changing of relations will be reason to rewrite many access check methods. I don't know which access calculations you want to implement.

So, you can do what you want, but I think you will get something new, not the_role gem.

**Comment by vtrkanna** [comment]
User has many Roles

ex: user can access admin and more features .
