### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by youcefdahmani** [TheRole/the_role_api#14]
Hi, I want to know if this gem can be used for a custom model, because on my project I don't use a User model but an Administrator model which can have different roles.

**Comment by the-teacher** [comment]
@youcefdahmani Hello!
I'm sorry, but I can't help you with it. Because of that:
https://github.com/TheRole/docs/blob/master/Limitations.md#only-user-model-supported
But you are welcome to add this functionality.
