### ISSUE TITLE
The role 3.0.3 published on rubygems doesnt includes the latest changes

### ISSUE THREAD

**Issue by neohunter** [TheRole/the_role_api#15]
Master apparently has 3.0.3 but the 3.0.3 version published on rubygems doesnt includes the latest change to avoid redirecting to :back

**Comment by the-teacher** [comment]
Hello! thanks for report. Yep, It can be so. I will try to find time to fix it.

**Comment by the-teacher** [comment]
Should be fixed now

Rails 5 supported:

https://rubygems.org/gems/the_role/versions/3.5
https://rubygems.org/gems/the_role_api/versions/3.5
https://rubygems.org/gems/the_role_management_panel/versions/3.5

Tested manually with https://github.com/TheRole/rails5dummy

```
gem 'the_role', '~> 3.5'
```
