### ISSUE TITLE
Глобальное переименование классов

### ISSUE THREAD

**Issue by the-teacher** [TheRole/the_role_api#5]
Я планирую изменить именацию классов и модулей

на данный момен оно выглядит вот так:

```ruby
module TheRole
   module User

   extend ActiveSupport::Concern

   include TheRole::Base
   end
end
```
Мне бы хотелось вот такого результата

```ruby
module TheRole
   module Api
     module User

     extend ActiveSupport::Concern

     include TheRole::Api::Base
     end
   end
end
```

Соответственно, должна поменятьсяс структура каталогов в папке `app` гема TheRoleApi
А в DummyApp и в доках `include TheRole::User` сменится на `include TheRole::Api::User`.

Аналогичные изменения должны произойти с другими модулями внутри гема. Т.е. с `TheRole::User` `TheRole::Base` `TheRole::Role`  и прочее.

В итоге кроме имен классов и модулей ничего не должно сломаться. Тесты должны проходить, так как они делают сейчас.

Задача может затронуть все компоненты проекта. Читай другую задачу, поясняющую процесс работы.

**Comment by sedx** [comment]
По поводу структуры каталогов, правильно ли я понял что теперь должно быть:
```
app/model/concerns/the_role/api
```
и еще вопрос
> Т.е. с TheRole::User TheRole::Base TheRole::Role и прочее.

прочее это те модули, что лежит в папке `lib\the_role` ?

**Comment by the-teacher** [comment]
@sedx `app/model/concerns/the_role/api` - да

> прочее это те модули, что лежит в папке lib\the_role ?
все что в TheRoleApi - в главном модуле должно быть внутри главного модуля `TheRole`.  Сейчас я вижу это так

**Comment by the-teacher** [comment]
@sedx Сообщи поджалуйста о статусе и планах на выходные. у меня скорее всего будет время и я хочу поработать над гемом.

**Comment by sedx** [comment]
@the-teacher Сегодня вечером сдамся в репозиторий по текущему тикету.
В субботу может будет свободное время (пока еще не знаю)
В Вс уезжаю за город, интернета не будет :)

**Comment by the-teacher** [comment]
@sedx ok. отлично. закинь что будет. Я планирую поработать в воскресенье. Так что если у меня будет твой код - будет отлично.

**Comment by the-teacher** [comment]
@sedx у меня было немного времени, я сделал ряд желаемых правок.

0. Переименование гема для UI
0. более информативные сообщения для json запросов
0. изменения в Dummy

думаю к вечеру еще успею привести Dummy в порядок. То что в репе может быть тяжело запустить с ходу.

потому 2 пояснения

0. если у тебя уже есть какие то наработки - не переживай, я постараюсь все что можно из твоего кода забрать
0. если только планируешь чем то заняться - то лучше дождись вечернего кода, пока я не подчищу черновик

**Comment by sedx** [comment]
@the-teacher ок) я в репозиторий TheRoleApi сдался уже, после сдачи чего-то у меня тесты на локальном компе не пошли.

Я тогд дождусь твоих правок вытяну и еще разок гляну в чем причина, сегодня вечером-завтра утром запушу оконательный результат.

**Comment by the-teacher** [comment]
@sedx все норм! :+1: тесты зеленые
Спасибо!

сейчас меня интересует несколько вопросов

0. Генераторы внутри гема. Их нужно растащить по нужным местам. Большую часть в UI меньшую часть в API
0. Замена HAML на SLIM в UI
0. Доработка UI с точки зрения JS и интерфейса
0. Документация

Можешь сделать обзор по данным задачам и если будет возможность в чем то поучаствовать.
Пока у меня более конкретных задач нет.

**Comment by sedx** [comment]
это хорошо!
Рад стараться)

1) посмотрел генераторы. Их там получается всего 4 штуки (`install`, `models`, `admin`, `config`).
 Я так понимаю в API надо оставить только `config` все остальные вынести в UI. Тут в принципе для меня нет ничего сложного, думаю с этим я справлюсь.

2) Со слимом раньше не встречался, только поглядывал на него. Но думаю это перкрасный повод в нем разобраться. Смонтирую две версии UI на разные роуты и постепенно смогу переписать.

3) Тут без проблем.

4) В английском не сильно шарю, но актуализировать инфу смогу.

Поучаствовать могу во всем, но самая вкусная задача с переходом на Slim)

**Comment by the-teacher** [comment]
@sedx

Предлагаю тебе перегнать шаблоны в SLIM. и заменить haml на slim в UI 

0. генераторы я почти доделал. эту задачу закрываем. не актулаьно
0. по UI/JS предлагаю пока отложить, мне надо понять что хочется доделать
0. по доке надо потихоньку двигаться, этот вопрос долгий.

На данный момент код считаю почти готовым к 3-му релизу. как только дока будет закончена оформим релиз.

**Comment by the-teacher** [comment]
Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!
