### ISSUE TITLE
Немного о процессе разработки

### ISSUE THREAD

**Issue by the-teacher** [TheRole/the_role_api#6]
Ты должен быть владельцем организации на равне со мной и должен уметь пушить (создавать свои ветки) в репозитории. Подтверди это или сообщи об обратном.

0. Для наиболее комфортного процесса разработки я советую тебе склонить в отдельную папку все 3 проекта из организации `TheRole`
0. В Gemfile DummyApp ты можешь указывать локальный путь г гему и конкретную ветку из которой будет использоваться код.
0. При выполнении глабальных правок сделай в кажом куске проекта отдельную ветку с одним и тем же названием. `issue_5_api_global_rename` ну или что то в таком духе
0. Завяжи DummyApp на эти ветки и свободно играйся с кодом. Запускай тесты и контролируй происходящее.
0. При завершении работы запуш все проекты кроме DummyApp (новые ветки с задачей) в основной репозиторий
0. Завяжи DummyApp на нужные ветки проектов на Github. забандли. Запусти тесты. и в запушь DummyApp в новую ветку.
0. Сразу после пуша новой ветки DummyApp начти следить на CI  и убедись, что во всех 36 окружениях тесты прошли.

По завершении задачи я заберу все новые ветки всех проектов, посмотрю, погоняю DummyApp и в итоге замержу твой код в `master`

Сообщи о вопросах если они есть.

**Comment by the-teacher** [comment]
@sedx было бы хорошо получить от тебя отклик в ближайшее время, что бы мне немного спланировать занятость.

спасибо!

**Comment by sedx** [comment]
в принципе все понятно. Просто не сталкивался раньше с пралельной разработкой нескольких гемов поэтому и смутился когда тесты начли падать.
пушить ветки я думаю тоже разберусь как (я так понимаю этот процесс идентичен тому как я пушил ветки в свой форк)

**Comment by the-teacher** [comment]
@sedx да. с ветками все так. можешь с нуля скачать проекты из основной репы или поменять удаленные источники в текущей локальной репе. Но лучше скачать с нуля.

**Comment by the-teacher** [comment]
@sedx репы в твоем профиле гитхаба по сути не нужны, если ты имеешь доступ к репам организации. в свои репы пушь код только если нужны зеленые квадратики активности. Все основные операции делай в репах организации.

**Comment by sedx** [comment]
@the-teacher я просто на работе если есть время что-то делаю, ну и дома. иногда "незаконченный" коммит делаю, чтобы дома продолжить. просто чтобы в основной репе не мусорить пушу в форки, а потом сквошу перед тем как в origin пушить.

и квадратики не дают если коммиты в форк сделаны) только либо за свои репозитории, или за PR в репозиторий проекта.

**Comment by the-teacher** [comment]
Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!
