### ISSUE TITLE
The Role + Rails API

### ISSUE THREAD

**Issue by giedriusr** [TheRole/the_role_api#8]
Hello,

What if I have `rails-api` type of application? I've tried to test one of the controllers and instead of giving unauthorized it tries to redirect to previous page, meaning, that it doesn't support it.

```ruby
ActionController::RedirectBackError:
       No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].
```

/cc @the-teacher

**Comment by the-teacher** [comment]
Hello! what about this?
https://github.com/TheRole/DummyApp/blob/master/spec/controllers/admin_roles_controller_spec.rb#L7

it is typical case for rspec

**Comment by giedriusr** [comment]
Not really. In rails-api apps there shouldn't be any redirects, but 401.

**Comment by the-teacher** [comment]
I have not expirience with Rails Api.
Try to clone repo and chache following line:

https://github.com/TheRole/the_role_api/blob/master/app/controllers/concerns/the_role/controller.rb#L49

it's the only point with `redirect`

**Comment by giedriusr** [comment]
Don't think that's what I'd like to do. Anyway, thanks a lot for your feedback and fast response!

**Comment by the-teacher** [comment]
@giedriusr please, let me know if problem solved
